steps:
   - name: python
     entrypoint: python
     args: ["-m", "pip", "install", "--upgrade", "pip"]     
   - name: python
     entrypoint: python
     args: ["-m", "pip", "install", "build", "pytest", "twine", "--user"]
   - name: python
     entrypoint: python
     args: ["-m", "pytest", 'tests/' ]
   - name: python
     id: "BUILD WHEEL"
     entrypoint: python
     args: ["-m", "build"]

   - name: python
     id: "push to pypi"
     entrypoint: python
     args:
     - '-m'
     - 'twine'
     - 'upload'
     - '--skip-existing'
     - '-r'
     - 'pypi'
     - "-u" 
     - "$_PYPI_USERNAME"
     - "-p" 
     - "$_PYPI_PASSWORD"
     - 'dist/*'
     waitFor: ["BUILD WHEEL"]

artifacts:
  objects:
    location: gs://paul-henry-tremblay-general/
    paths:
      - "dist/*"
